apiVersion: apps/v1
kind: Deployment
metadata:
  name: exams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exams
  template:
    metadata:
      labels:
        app: exams
    spec:
      containers:
        - name: exams
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
